language: android
jdk: oraclejdk8
sudo: required
android:
  components:
    -tools
    -platform-tools

    # The BuildTools version used by your project
    -build-tools-26.0.2

    # The SDK version used to compile your project
    - android-26
    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
os:
  - linux
after_success:
  - python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)

notifications:
    slack: sdsmdg:hBRszERiXBQVCRKHljR1Ilwk
script:
  - ./gradlew build
  - ./gradlew test